# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gc_JugjleuOpu-rQrQVDmrHZtWdAcuGZ
"""



import os
from typing import Optional
import streamlit as st
from huggingface_hub import InferenceClient
from nba_api.stats.static import players
from nba_api.stats.endpoints import PlayerGameLog

# -----------------------
# Auth / Model selection
# -----------------------
HF_TOKEN = os.environ.get("HF_TOKEN")
if not HF_TOKEN:
    st.warning("Set your Hugging Face token first:\nexport HF_TOKEN='hf_xxx'\nthen rerun app.")
    st.stop()

MODEL_NAME = "google/gemma-2-2b-it"
client = InferenceClient(model=MODEL_NAME, token=HF_TOKEN)

# -----------------------
# Prompts (vibe switch)
# -----------------------
DEFAULT_PROMPT = """
You are CourtSide Bestie — friendly, clear, hype, and non-condescending.
Define any stat in plain English, then add one simple analogy.
Keep it short (3–6 sentences) and say if a number is great, average, or bad vs typical NBA standards.
"""

DRAMA_PROMPT = """
You are CourtSide Bestie — the courtside commentator with the energy of a reality TV confessional.
Define the stat in plain English, then add 1–2 fun reality-TV metaphors.
Keep it juicy and concise (2–4 sentences) and label numbers as serving / mid / messy vs NBA standards.
No mansplaining.
"""

MAKEUP_PROMPT = """
You are CourtSide Bestie — explain hoops with Sephora vibes.
Define the stat in simple English, then use 1 makeup analogy (blend, coverage, flawless finish, etc.).
Keep it 3–5 sentences and say if the number is elite, average, or low vs league norms.
"""

VIBES = {
    "Classic": DEFAULT_PROMPT,
    "Drama TV": DRAMA_PROMPT,
    "Makeup": MAKEUP_PROMPT,
}

# -----------------------
# NBA helpers
# -----------------------
def get_player_id(name: str):
    m = players.find_players_by_full_name(name)
    return m[0]["id"] if m else None


def get_recent_stats(player_name: str, season: str = "2024-25", last_n: int = 10):
    pid = get_player_id(player_name)
    if not pid:
        return None

    df = PlayerGameLog(player_id=pid, season=season).get_data_frames()[0]
    if df.empty:
        return None

    logs = df.head(last_n)  # nba_api returns most recent first
    pts = logs["PTS"].mean()
    reb = logs["REB"].mean()
    ast = logs["AST"].mean()
    fga = logs["FGA"].sum()
    fta = logs["FTA"].sum()
    total_pts = logs["PTS"].sum()

    ts = None
    denom = (fga + 0.44 * fta)
    if denom > 0:
        ts = total_pts / (2 * denom)

    return {
        "games_considered": int(len(logs)),
        "ppg": round(pts, 1),
        "rpg": round(reb, 1),
        "apg": round(ast, 1),
        "ts": round(ts * 100, 1) if ts is not None else None,
    }


def build_prompt(question: str, player_name: Optional[str], stats: Optional[dict]) -> str:
    """Combine question + stats into one prompt string for the model."""
    context = ""
    if player_name and stats:
        ts_val = f"{stats['ts']}%" if stats.get("ts") is not None else "N/A"
        context = f"""
Player: {player_name}
Last {stats['games_considered']} games:
- Points per game (PPG): {stats['ppg']}
- Rebounds per game (RPG): {stats['rpg']}
- Assists per game (APG): {stats['apg']}
- True Shooting % (TS%): {ts_val}
"""
    return f"""
User question:
{question}

Context (if helpful):
{context}
"""


def explain_with_hf(system_prompt: str,
                    question: str,
                    player_name: Optional[str],
                    season: str,
                    max_tokens: int = 180,
                    temperature: float = 0.75):
    """Fetch stats, build prompt, send to model, and return text + stats."""
    stats = get_recent_stats(player_name, season=season) if player_name else None
    user_content = build_prompt(question, player_name, stats)

    resp = client.chat_completion(
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content},
        ],
        max_tokens=max_tokens,
        temperature=temperature,
    )

    choice = resp.choices[0]
    msg = choice.message
    text = msg["content"] if isinstance(msg, dict) else msg.content
    return text.strip(), stats

# -----------------------
# UI
# -----------------------
st.set_page_config(page_title="CourtSide Bestie", page_icon="🏀", layout="centered")
st.title("🏀 CourtSide Bestie")
st.caption("LLM + NBA stats (via nba_api) with an inclusive, fun explainer vibe.")

with st.sidebar:
    st.header("Settings")
    vibe = st.selectbox("Vibe", list(VIBES.keys()), index=1)
    season = st.text_input("Season (YYYY-YY)", "2024-25")
    last_n = st.slider("Last N games", min_value=5, max_value=20, value=10, step=1)
    temperature = st.slider("Drama level (temperature)", 0.0, 1.2, 0.75, 0.05)
    max_tokens = st.slider("Max tokens", 80, 300, 180, 10)
    show_stats = st.checkbox("Show stats context", value=True)
    st.markdown("---")
    st.markdown("**Auth**")
    st.write(f"Model: `{MODEL_NAME}`")
    st.write("HF_TOKEN found ✅" if HF_TOKEN else "HF_TOKEN missing ❌")

st.subheader("Ask a question")
question = st.text_input("Your question", "What is True Shooting % and is this good for Shai?")
player_name = st.text_input("Player (optional)", "Shai Gilgeous-Alexander")

if st.button("Explain"):
    with st.spinner("Breaking it down…"):
        try:
            answer, stats_used = explain_with_hf(
                system_prompt=VIBES[vibe],
                question=question,
                player_name=player_name.strip() or None,
                season=season,
                max_tokens=max_tokens,
                temperature=temperature,
            )
        except Exception as e:
            st.error(f"Error: {e}")
        else:
            if show_stats and stats_used:
                st.markdown(
                    f"**📊 Last {stats_used['games_considered']} games** — "
                    f"PPG: **{stats_used['ppg']}**, RPG: **{stats_used['rpg']}**, "
                    f"APG: **{stats_used['apg']}**, TS%: **{stats_used['ts']}**"
                )
            st.markdown("### 💅 CourtSide Bestie says")
            st.write(answer)

st.markdown("---")
st.caption("Built with Streamlit • Hugging Face Inference • nba_api")